import type { IEEEDomain } from './types'

export const domains: IEEEDomain[] = [
  {
    id: 'cs',
    name: 'Computer Society',
    acronym: 'CS',
    tagline: 'Computing the future',
    description:
      'The IEEE Computer Society is the premier organisation for computing professionals. It drives advancements in computing technology, software engineering, cybersecurity, and artificial intelligence — connecting researchers, practitioners, and students worldwide.',
    activities: [
      'Competitive programming and hackathon preparation',
      'Open-source project contribution drives',
      'Machine Learning study circles and paper reviews',
      'Cybersecurity CTF (Capture The Flag) competitions',
      'AI/ML workshops: neural networks, LLMs, computer vision',
    ],
    color: '#00D4FF',
    iconName: 'Cpu',
    memberCount: '100,000+ members',
  },
  {
    id: 'pes',
    name: 'Power & Energy Society',
    acronym: 'PES',
    tagline: 'Powering the planet sustainably',
    description:
      'PES focuses on the generation, transmission, and distribution of electric power — and increasingly, the transition to renewable and smart-grid technologies. Members work on solar, wind, grid resilience, and energy storage systems.',
    activities: [
      'Renewable energy project design challenges',
      'Smart grid simulation workshops',
      'Power electronics hands-on labs',
      'Industry site visits to power plants and substations',
      'Climate tech and energy policy panel discussions',
    ],
    color: '#FFB300',
    iconName: 'Lightning',
    memberCount: '30,000+ members',
  },
  {
    id: 'ras',
    name: 'Robotics & Automation Society',
    acronym: 'RAS',
    tagline: 'Building machines that think and move',
    description:
      'RAS is at the frontier of intelligent machines. Members design, build, and program autonomous systems — from warehouse robots to surgical assistants — using principles of kinematics, control theory, and embedded AI.',
    activities: [
      'Robot design and build competitions',
      'ROS (Robot Operating System) workshops',
      'Drone programming and autonomous navigation labs',
      'Computer vision for robotic perception projects',
      'Industry collaboration with automation companies',
    ],
    color: '#7B61FF',
    iconName: 'Robot',
    memberCount: '12,000+ members',
  },
  {
    id: 'sp',
    name: 'Signal Processing Society',
    acronym: 'SP',
    tagline: 'Making sense of data',
    description:
      'Signal processing is the mathematics of extracting meaning from data — audio, images, biomedical signals, radar, and more. The SP Society connects members working on DSP algorithms, communications systems, and data-driven sensing.',
    activities: [
      'Digital signal processing project workshops',
      'Audio and image processing hackathons',
      'Speech recognition and synthesis projects',
      'MATLAB and Python DSP toolkit training',
      'Research paper reading groups',
    ],
    color: '#00E5A0',
    iconName: 'Waveform',
    memberCount: '18,000+ members',
  },
  {
    id: 'comsoc',
    name: 'Communications Society',
    acronym: 'ComSoc',
    tagline: 'Connecting the world',
    description:
      'ComSoc advances the theory and practice of communications and networking — from 5G and satellite networks to fibre optics and IoT. Members work on protocols, network architectures, and the wireless systems that underpin modern life.',
    activities: [
      '5G and next-gen wireless technology seminars',
      'Network simulation and protocol design labs',
      'IoT project challenges',
      'Telecommunications industry speaker series',
      'Packet networking and SDN workshops',
    ],
    color: '#00D4FF',
    iconName: 'WifiHigh',
    memberCount: '25,000+ members',
  },
  {
    id: 'emc',
    name: 'Electromagnetic Compatibility Society',
    acronym: 'EMC',
    tagline: 'Taming invisible interference',
    description:
      'EMC ensures electronic devices co-exist without degrading each other\'s performance. It\'s a precision discipline spanning PCB design, antenna theory, shielding, and regulatory compliance — essential for every product that reaches market.',
    activities: [
      'PCB design for EMC compliance workshops',
      'Antenna design and simulation projects',
      'Regulatory standards (FCC, CE) training',
      'RF measurement and spectrum analysis labs',
    ],
    color: '#FF4757',
    iconName: 'BroadcastIcon',
    memberCount: '8,000+ members',
  },
  {
    id: 'embs',
    name: 'Engineering in Medicine & Biology Society',
    acronym: 'EMBS',
    tagline: 'Engineering at the edge of life',
    description:
      'EMBS is where electrical engineering meets biology and medicine. Members develop medical devices, diagnostic equipment, neural interfaces, and health monitoring systems — technologies that save lives and transform healthcare.',
    activities: [
      'Biosignal processing: ECG, EEG, EMG workshops',
      'Wearable health tech build projects',
      'Medical imaging fundamentals (MRI, CT, ultrasound)',
      'Healthcare AI and diagnostic algorithm development',
      'Collaboration with medical institutions',
    ],
    color: '#00E5A0',
    iconName: 'Heart',
    memberCount: '11,000+ members',
  },
  {
    id: 'aes',
    name: 'Aerospace & Electronic Systems Society',
    acronym: 'AESS',
    tagline: 'Systems that fly and navigate',
    description:
      'AESS covers the electronics that make aerospace work: radar, navigation, avionics, and electronic warfare. Members engage with the full stack from system design to embedded control — for everything from drones to deep-space probes.',
    activities: [
      'Radar systems fundamentals workshops',
      'Drone systems design and flight controller programming',
      'Navigation algorithms: GPS, INS, Kalman filtering',
      'Aerospace systems simulation labs',
    ],
    color: '#7B61FF',
    iconName: 'AirplaneTakeoff',
    memberCount: '6,000+ members',
  },
  {
    id: 'ie',
    name: 'Industrial Electronics Society',
    acronym: 'IES',
    tagline: 'Powering industry with intelligence',
    description:
      'IES bridges electronics and manufacturing — covering motor drives, industrial automation, power converters, and smart factory systems. The Society is central to Industry 4.0, IIoT, and the electrification of industrial processes.',
    activities: [
      'Motor control and variable frequency drive labs',
      'PLC (Programmable Logic Controller) programming',
      'Industry 4.0 and IIoT project workshops',
      'Power converter design challenges',
      'Factory automation site visits',
    ],
    color: '#FFB300',
    iconName: 'Factory',
    memberCount: '9,000+ members',
  },
  {
    id: 'wc',
    name: 'Women in Engineering',
    acronym: 'WIE',
    tagline: 'Every voice in engineering matters',
    description:
      'IEEE WIE is one of the largest international communities dedicated to inspiring and engaging women in engineering and science. WIE runs mentorship programmes, leadership development, and community initiatives that make engineering more inclusive.',
    activities: [
      'Mentorship pairing with senior engineers',
      'Leadership and professional development workshops',
      'Networking events with industry professionals',
      'Outreach programmes for school students',
      'Community panel discussions on inclusion in STEM',
    ],
    color: '#FF4757',
    iconName: 'UsersThree',
    memberCount: '20,000+ members',
  },
]
